version: '3.9'

services:
  app:
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    build: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - port=27017
      - host=db
      - directConnection=1

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
